#!/usr/bin/env python3
import linkify

# the expected values match whatever the discord client does as of 2019-03-02

no_match = [
	# https://mathiasbynens.be/demo/url-regex
	"http://",
	"http://.",
	"http://..",
	"http://?",
	"http://??",
	"http://??/",
	"http://#",
	"http://##",
	"http://##/",
	"//",
	"//a",
	"///a",
	"///",
	"http:///a",
	"foo.com",
	"rdar://1234",
	"h://test",
	"http:// shouldfail.com",
	":// should fail",
	"ftps://foo.bar/",
	"ftp://foo.bar/baz",

	"HTTP://example.com/",
	"HTTP://-error-.inVAlid/",
	"http://\:fox:/",
	"http:// 🦊/",
	"http://\🦊/",
	"http://[woof][/",
	"http://[woof][🦊]",
	"http://[woof][🦊][http:/]/",
	"http://[woof][🦊][http:[][][]][][][]",
	"http://[woof][🦊][http:[][][]][][][][/",
	"http://[woof][🦊][http:[[[&(*(&!!(($)$!(([[[;[[[[]/",
	"http://[woof][🦊][http:[[[&(*(&!!(($)$!(([[[?[[[[]/",
	"example.com/woof/",
]

same_match = [
	# https://mathiasbynens.be/demo/url-regex
	"http://../",
	"http://-error-.invalid/",
	"http://a.b--c.de/",
	"http://-a.b.co/",
	"http://a.b-.co/",
	"http://0.0.0.0/",
	"http://10.1.1.0/",
	"http://10.1.1.255/",
	"http://224.1.1.1/",
	"http://1.1.1.1.1/",
	"http://123.123.123/",
	"http://3628126748/",
	"http://.www.foo.bar/",
	"http://www.foo.bar./",
	"http://.www.foo.bar./",
	"http://10.1.1.1/",
	"http://10.1.1.254/",
	"http://foo.com/blah_blah",
	"http://foo.com/blah_blah/",
	"http://foo.com/blah_blah_(wikipedia)",
	"http://foo.com/blah_blah_(wikipedia)_(again)",
	"http://www.example.com/wpstyle/?p=364",
	"https://www.example.com/foo/?bar=baz&inga=42&quux",
	"http://142.42.1.1/",
	"http://142.42.1.1:8080/",
	"http://foo.com/blah_(wikipedia)#cite-1",
	"http://foo.com/blah_(wikipedia)_blah#cite-1",
	"http://foo.com/unicode_(✪)_in_parens",
	"http://foo.com/(something)?after=parens",
	"http://code.google.com/events/#&product=browser",
	"http://foo.bar/?q=Test%20URL-encoded%20stuff",
	"https://foo_bar.example.com/",
	"http://xn--fsqu00a.xn--0zwm56d/",
	"http://223.255.255.woof/",
	"http://255.255.255.255/",
	"http://woof.woof.woof.255/",
	"http://woof_woof.com/",
	"http://[2001::f00f]/",
	"http://[2001:aaaa:aaaa:aaaa:aaaa:aaaa:aaaa:aaaa:f00f]/",
	"http://[::ffff:7f00:1]:8000/",
	"http://[::ffff:127.0.0.1]:8000/",
	"http://[::ffffh:::asdfasdf:]/",
	"http://[woof]/",
	"http://[example.com]/",
	"http://[woof][]/",
	"http://[woof][🦊]/",
	"http://[woof][🦊][http:[][][]][][][]/",
	"http://[woof][🦊][http:[[[[[[[[[[]/",
	"http://[woof][🦊][http:[[[&(*(&!!(($)$!(([[[[[[[]/",
	"http://[woof][🦊][http:[[[&(*(&!!$$!(([[[:[[[[]/",
	'http://".com/',
	"http://'.com/",
]

match = [
	# https://mathiasbynens.be/demo/url-regex
	"http://foo.bar/?q=Spaces should be encoded", '<a href="http://foo.bar/?q=Spaces">http://foo.bar/?q=Spaces</a>',
	"http://foo.bar/foo(bar)baz quux", '<a href="http://foo.bar/foo(bar)baz">http://foo.bar/foo(bar)baz</a>',

	"http://j.mp", '<a href="http://j.mp/">http://j.mp/</a>',
	"http://1337.net", '<a href="http://1337.net/">http://1337.net/</a>',
	"http://a.b-c.de", '<a href="http://a.b-c.de/">http://a.b-c.de/</a>',
	"http://223.255.255.254", '<a href="http://223.255.255.254/">http://223.255.255.254/</a>',

	"http://userid:password@example.com:8080", '<a href="http://userid:password@example.com:8080/">http://example.com:8080/</a>',
	"http://userid:password@example.com:8080/", '<a href="http://userid:password@example.com:8080/">http://example.com:8080/</a>',
	"http://userid@example.com", '<a href="http://userid@example.com/">http://example.com/</a>',
	"http://userid@example.com/", '<a href="http://userid@example.com/">http://example.com/</a>',
	"http://userid@example.com:8080", '<a href="http://userid@example.com:8080/">http://example.com:8080/</a>',
	"http://userid@example.com:8080/", '<a href="http://userid@example.com:8080/">http://example.com:8080/</a>',
	"http://userid:password@example.com", '<a href="http://userid:password@example.com/">http://example.com/</a>',
	"http://userid:password@example.com/", '<a href="http://userid:password@example.com/">http://example.com/</a>',

	"http://✪df.ws/123", '<a href="http://xn--df-oiy.ws/123">http://xn--df-oiy.ws/123</a>',
	"http://➡.ws/䨹", '<a href="http://xn--hgi.ws/䨹">http://xn--hgi.ws/䨹</a>',
	"http://⌘.ws", '<a href="http://xn--bih.ws/">http://xn--bih.ws/</a>',
	"http://⌘.ws/", '<a href="http://xn--bih.ws/">http://xn--bih.ws/</a>',
	"http://☺.damowmow.com/", '<a href="http://xn--74h.damowmow.com/">http://xn--74h.damowmow.com/</a>',
	"http://مثال.إختبار", '<a href="http://xn--mgbh0fb.xn--kgbechtv/">http://xn--mgbh0fb.xn--kgbechtv/</a>',
	"http://例子.测试", '<a href="http://xn--fsqu00a.xn--0zwm56d/">http://xn--fsqu00a.xn--0zwm56d/</a>',
	"http://उदाहरण.परीक्षा", '<a href="http://xn--p1b6ci4b4b3a.xn--11b5bs3a9aj6g/">http://xn--p1b6ci4b4b3a.xn--11b5bs3a9aj6g/</a>',
	"http://-.~_!$&\'()*+,;=:%40:80%2f::::::@example.com", '<a href="http://-.~_!%24%26\'()*%2B%2C%3B%3D:%40%3A80%2F%3A%3A%3A%3A%3A%3A@example.com/">http://example.com/</a>',

	"http://-error-.inVAlid/", '<a href="http://-error-.invalid/">http://-error-.invalid/</a>',
	"http://223.255.255.wOOF/", '<a href="http://223.255.255.woof/">http://223.255.255.woof/</a>',
	"http://🦊/", '<a href="http://xn--9s9h/">http://xn--9s9h/</a>',
	"http://[woof][🦊][http:[[[&(*(&!!$$!(([[[@[[[[]/", '<a href="http://%5Bwoof%5D%5B%F0%9F%A6%8A%5D%5Bhttp:%5B%5B%5B%26(*(%26!!%24%24!((%5B%5B%5B@[[[[]/">http://[[[[]/</a>',
	"http://a'n.com", '<a href="http://a/%27n.com/">http://a/%27n.com/</a>',
	'http://a"n.com', '<a href="http://a/%22n.com/">http://a/%22n.com/</a>',
	"http://user@user@example.com/", '<a href="http://user@user@example.com/">http://example.com/</a>',
	"http://user@user:pass.example.com/", '<a href="http://user@user/:pass.example.com/">http://user/:pass.example.com/">
	"http://user:pass:pass.example.com/", '<a href="http://user/:pass:pass.example.com/">http://user/:pass:pass.example.com/</a>',
	"http://user:pass:pass@example.com/", '<a href="http://user:pass:pass@example.com/">http:/example.com/">
]
